services:
  banco:
    image: mysql:8.0
    container_name: salao_mysql
    restart: always
    environment:
      MYSQL_DATABASE: Belleza
      MYSQL_ROOT_PASSWORD: "Curitiba"
    ports:
      - "3309:3306"
    volumes:
      - dados_salao:/var/lib/mysql
      - ./banco/beleza.sql:/docker-entrypoint-initdb.d/beleza.sql

volumes:
  dados_salao: